In [3]:
# mengulang list sebanyak tiga kali
# ini terjadi karena yang dikalikan adalah list bukan vektor
[1, 2, 3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [4]:
# list dengan list hasilnya error
[1, 2, 3] * [4, 5, 6]

TypeError: can't multiply sequence by non-int of type 'list'

# Numerical Python (Numpy)

In [6]:
import numpy as np

In [2]:
a = numpy.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
a * 3

array([3, 6, 9])

# Math Functions

In [7]:
np.sum(a)

6

In [8]:
np.mean(a)

2.0

In [9]:
np.std(a)

0.816496580927726

In [10]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

# arange, linspace, logspace

In [13]:
np.arange(0,5, 0.2)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4,
       2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8])

In [14]:
np.arange(0, 5)

array([0, 1, 2, 3, 4])

In [20]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [21]:
np.logspace(-3, 3, 7)

array([1.e-03, 1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])

# Random

In [34]:
np.random.rand(3, 2) # 3 baris dan 2 kolom dengan angka acak

array([[0.73674736, 0.19107291],
       [0.35605396, 0.00287053],
       [0.86943501, 0.37239467]])

# Controlled Randomness

In [35]:
# mengacak number dengan hasil sama untuk setiap user

In [36]:
state = np.random.RandomState(42)
state.rand(3)

array([0.37454012, 0.95071431, 0.73199394])